@extends('layouts.app')

@section('title', 'Recommendations')

@php($active = 'recommendations')

@section('content')
<div class="patients-page">

    <div class="patients-page__head">
        <div>
            <h1>Recommendations List</h1>
            <p>Review recommendations generated by the clinical decision engine for each consultation.</p>
        </div>
    </div>

    {{-- ================= Stat cards ================= --}}
    <div class="dashboard-stats dashboard-stats--compact">

        <div class="dashboard-stat-card">
            <span class="dashboard-stat-card__icon">
                <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="5" y="3" width="14" height="18" rx="2" stroke="currentColor" stroke-width="1.6"/><path d="M9 3h6v3H9z" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"/></svg>
            </span>
            <div class="dashboard-stat-card__body">
                <h3>Recommendations</h3>
                <strong>{{ $pendingCount }}</strong>
                <span>Awaiting review</span>
            </div>
        </div>

        <div class="dashboard-stat-card">
            <span class="dashboard-stat-card__icon">
                <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="5" y="3" width="14" height="18" rx="2" stroke="currentColor" stroke-width="1.6"/><path d="M8 12l2.5 2.5L16 9" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg>
            </span>
            <div class="dashboard-stat-card__body">
                <h3>Recommendations</h3>
                <strong>{{ count($recommendations) }}</strong>
                <span>In the system</span>
            </div>
        </div>

    </div>

    <div class="patients-toolbar">
        <div class="patients-toolbar__search">
            <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><circle cx="11" cy="11" r="7" stroke="currentColor" stroke-width="2"/><path d="M21 21l-4.3-4.3" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>
            <input type="search" placeholder="Search by patient name or ID...">
        </div>

        <div class="patients-toolbar__filter">
            <span>Status</span>
            <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M6 9l6 6 6-6" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
        </div>
        <div class="patients-toolbar__filter">
            <span>Stage</span>
            <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M6 9l6 6 6-6" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
        </div>

        <button type="button" class="patients-toolbar__reset">
            Reset
            <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M3 12a9 9 0 1 1 3 6.7" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/><path d="M3 8v5h5" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg>
        </button>
    </div>

    <div class="patients-table-wrap">
        <table class="patients-table">
            <thead>
                <tr>
                    <th>Patient ID</th>
                    <th>Patient Name</th>
                    <th>Age</th>
                    <th>Status</th>
                    <th>Stage</th>
                    <th>Last Updated</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($recommendations as $rec)
                <tr>
                    <td>{{ $rec['patient_id'] }}</td>
                    <td>{{ $rec['patient_name'] }}</td>
                    <td>{{ $rec['age'] }}</td>
                    <td><span class="patients-table__status">{{ $rec['status'] }}</span></td>
                    <td>{{ $rec['stage_label'] }}</td>
                    <td>{{ $rec['updated_at'] }}</td>
                    <td>
                        <div class="patients-table__actions">
                            <a href="{{ route('recommendations.show', $rec['id']) }}" aria-label="View recommendation">
                                <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M1.5 12S5 5 12 5s10.5 7 10.5 7-3.5 7-10.5 7-10.5-7-10.5-7Z" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"/><circle cx="12" cy="12" r="3" stroke="currentColor" stroke-width="1.6"/></svg>
                            </a>
                            <button type="button" aria-label="More options">
                                <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M6 9l6 6 6-6" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
                            </button>
                        </div>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <a href="#" class="patients-page__view-all">View All Recommendations </a>

</div>
@endsection
